### ISSUE TITLE
Awesome! But off center

### ISSUE THREAD

**Issue by dzg** [etiennepinchon/aframe-rounded#7]
This is great, but the center of the plane seems to be in the corner, not the center.
So if I want to keep positioning consistent with other entities, I have to shift position by ½ of the width/height.
Any way to get the center in the center automatically?
Thanks!

**Comment by dzg** [comment]
I see that `function roundedRect` starts at x,y then moves around ... I will rework this so the coordinates originate from center and report back.

**Comment by dzg** [comment]
Got it, just need to add this

```
      x -= width / 2
      y -= height / 2
```

right before

```
      ctx.moveTo(x, y + topLeftRadius)
```

**Comment by vincentfretin** [comment]
see also #1
